name: PNPM + Wireit CI

defaults:
  run:
    working-directory: ./pnpm-wireit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    # TODO(pnpm-wireit): Use wireit cache for build stuff.
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: true

      # Wireit cache
      - uses: google/wireit@setup-github-actions-caching/v1

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Generate lots of source files for build time assessment
        run: pnpm run generate
        working-directory: ./

      - name: Build
        run: pnpm run build
