name: PNPM + Wireit Release

defaults:
  run:
    working-directory: ./pnpm-wireit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: "echo TODO IMPLEMENT CHANGESETS ACTION"
