name: PNPM + Wireit Release

defaults:
  run:
    working-directory: ./pnpm-wireit

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          cache: true

      - name: TODO DEBUG REMOVE
        run: |
          node -e "console.log('process.cwd(): ', process.cwd())"

      # Wireit cache
      - uses: google/wireit@setup-github-actions-caching/v1

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # Not needed in normal project. Looks like working-directory is ignored.
          cwd: ./pnpm-wireit
          version: pnpm run version
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
