name: PNPM CI

defaults:
  run:
    working-directory: ./pnpm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      # TODO: REMOVE DEBUG
      - run: |
          echo $PWD
          ls

      - uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
